Feature/successful match event
Jesse-Cameron/robogals-initiative-1 pull request #14
Opened 2018-11-07 03:03 UTC by Jiacomina

Add collision detection event to falling blocks

2018-11-07 10:21 UTC, Jesse-Cameron commented on assets/Script/game/fallingBlock.js
> +      // const fadeOut = cc.fadeOut(this.fadeOutTime);
would you mind removing these old comments?

2018-11-07 10:33 UTC, Jesse-Cameron commented on assets/Script/game/fallingBlock.js
> -    if (this.movingVertical) {
This line will need to be re-added.
Essentially, when the block is being dragged the falling animation will stop.

2018-11-07 10:36 UTC, Jesse-Cameron commented on assets/Script/game/fallingBlock.js
> +    blockType: 'blue'
Until we settle on how to do the 'block matching', might be worth leaving this out.

2018-11-07 10:37 UTC, Jesse-Cameron requested changes
Overall, works perfectly. Just a couple of minor semantic changes!

2018-11-17 12:04 UTC, Jiacomina commented
Thanks Jesse, changes have been made

2018-11-18 04:36 UTC, Jesse-Cameron approved these changes
:fireworks:

2018-11-18 12:24 UTC, merged